### ISSUE TITLE
Integration into puNES emulator.

### ISSUE THREAD

**Issue by punesemu** [LMP88959/PAL-CRT#2] opened 2023-10-12 12:47 UTC
This time too you did a great job, I started to integrate the filter except that there are some things I would like to ask you. First, I have the same warnings I had with NTSC-CRT, could you take a look at it?
Second, using pal.c the output image I get is "deformed" as if it were stretched, look at the screenshot I attached to understand better, could it depend on the input image which has a size of 256x240? I would solve the problem using pal_nes.c (the output image is perfect) only I would lose the possibility of using the palette that the user can change in the video settings because in this mode the color of each pixel is calculated by decoding the 'pixel 6-bit or 9-bit NES. Wouldn't it be possible to use the palette color as in PAL_SYSTEM_PAL mode?
![PAL-CRT-01](https://github.com/LMP88959/PAL-CRT/assets/14859058/78c4fa49-bfb6-4ad8-aadb-549ff9d9308d)

**Comment by LMP88959** [comment] 2023-10-12 14:48
Yes, please tell me what warnings you have with NTSC-CRT?

Also I have a few questions:
1. Do you use CRT_SYSTEM_NTSC for the NTSC-CRT filter or CRT_SYSTEM_NES?
2. I'm not sure what stretching/deforming you see? I believe PAL should have a different aspect ratio than NTSC.
3. When you don't use PAL_SYSTEM_NES, do you still see the NES-specific composite artifacts?

I don't have direct support for palettes in either the NTSC or PAL filters but I do have hue parameters for both. In the PAL_SETTINGS struct in pal_nes.h and in the NTSC_SETTINGS struct in crt_nes.h.
I personally recommend using the NES versions of the filters because they are more realistic.

**Comment by punesemu** [comment] 2023-10-12 15:46
I apologize if I can't explain myself well but English is not my native language.

>Yes, please tell me what warnings you have with NTSC-CRT?

```
====================[ Build | punes | debug ]===================================
/home/sviluppo/clion-2022.2.4/bin/cmake/linux/x64/bin/cmake --build /home/sviluppo/personale/punes/build/clion/debug --target punes -j 14
[4/5] Building C object src/CMakeFiles/punes.dir/extra/PAL-CRT/pal_core.c.o
/home/sviluppo/personale/punes/src/extra/PAL-CRT/pal_core.c: In function ‘init_eq’:
/home/sviluppo/personale/punes/src/extra/PAL-CRT/pal_core.c:184:25: warning: right shift count is negative [-Wshift-count-negative]
  184 |         f->lf = 2 * (sn >> (15 - EQ_P));
      |                         ^~
/home/sviluppo/personale/punes/src/extra/PAL-CRT/pal_core.c:190:25: warning: right shift count is negative [-Wshift-count-negative]
  190 |         f->hf = 2 * (sn >> (15 - EQ_P));
      |                         ^~
/home/sviluppo/personale/punes/src/extra/PAL-CRT/pal_core.c: In function ‘pal_demodulate’:
/home/sviluppo/personale/punes/src/extra/PAL-CRT/pal_core.c:494:31: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
  494 |         for (pos = scanL; pos < scanR && cL < cR; pos += dx) {
```
same warnings that you have fixed with https://github.com/LMP88959/NTSC-CRT/commit/fe0ab638625efcfe666740b2f5b776bccb0cd1e0
> Do you use CRT_SYSTEM_NTSC for the NTSC-CRT filter or CRT_SYSTEM_NES?

I used CRT_SYSTEM_NTSC.

>I'm not sure what stretching/deforming you see? I believe PAL should have a different aspect ratio than NTSC.

Look at the word MARIO in the top left, you will be able to see that the first row of pixels at the top is stretched while the last row of pixels is compressed. You can see the same thing on the writing "1 PLAYER GAME" as well as in many other areas of the image. If I use PAL_SYSTEM_PAL these "defects" do not exist. I know that PAL and NTSC have a different aspect ratio but to perform the integration I disabled it in the emulator. Does your filter apply the aspect ratio to the input image?

>I don't have direct support for palettes in either the NTSC or PAL filters but I do have hue parameters for both. In the PAL_SETTINGS struct in pal_nes.h and in the NTSC_SETTINGS struct in crt_nes.h.
>I personally recommend using the NES versions of the filters because they are more realistic.

Maybe I didn't explain myself well regarding the color palette. In PAL_SYSTEM_PAL and CRT_SYSTEM_NTSC I give you the image in RGBA format as input. In the image that I give you as input I have already translated the NES pixel (9 bit) into a color and this color is chosen based on a palette that can be customized by the user. In PAL_SYSTEM_NES mode, however, you worry about decoding the NES pixel in the output format, so whatever palette the user chooses will not matter, it will never be taken into consideration.

**Comment by LMP88959** [comment] 2023-10-12 15:59
I updated the PAL-CRT code to fix those warnings, they were the same warnings that NTSC-CRT had.

>I used CRT_SYSTEM_NTSC.

You should use CRT_SYSTEM_NES and PAL_SYSTEM_NES. You should give the filters the 9-bit NES pixels, not RGB pixels.  
>so whatever palette the user chooses will not matter

I don't have custom palette support, but you should make the `hue` parameter in the `PAL_SETTINGS` and `NTSC_SETTINGS` structs available to the user in that options menu.

**Comment by punesemu** [comment] 2023-10-12 16:50
Ok, many thx.

**Comment by punesemu** [comment] 2023-10-12 17:45
Commited https://github.com/punesemu/puNES/commit/458cfa19f886cfabd0257cc72d76752beb642b98.

**Comment by LMP88959** [comment] 2023-10-12 17:49
Awesome work! I will try it out on my Windows machine soon.

**Comment by LMP88959** [comment] 2023-10-12 18:08
> Commited [punesemu/puNES@458cfa1](https://github.com/punesemu/puNES/commit/458cfa19f886cfabd0257cc72d76752beb642b98).

Oh you are still using the CRT_SYSTEM_NTSC and PAL_SYSTEM_PAL. These do not produce the proper NES artifacts.
You need to change in `pal_core.h`:
```c
#define PAL_SYSTEM PAL_SYSTEM_PAL
```
to 
```c
#define PAL_SYSTEM PAL_SYSTEM_NES
```
And then give the 9-bit NES pixels to the pal_modulate function.

And the same for the NTSC filter.

Change in `crt_core.h`:
```c
#define CRT_SYSTEM CRT_SYSTEM_NTSC
```
to 
```c
#define CRT_SYSTEM CRT_SYSTEM_NES
```
And then give the 9-bit NES pixels to the crt_modulate function.

**Comment by punesemu** [comment] 2023-10-12 18:23
>Oh you are still using the CRT_SYSTEM_NTSC and PAL_SYSTEM_PAL. These do not produce the proper NES artifacts.

It's true but only to be able to maintain the possibility of choosing the color palette (it's widely used by emu maniacs like me). The hue parameter can't help me in this case.

>You need to change in pal_core.h:
>
>#define PAL_SYSTEM PAL_SYSTEM_PAL
>to
>
>#define PAL_SYSTEM PAL_SYSTEM_NES
>And then give the 9-bit NES pixels to the pal_modulate function.
>
>And the same for the NTSC filter.
>
>Change in crt_core.h:
>
>#define CRT_SYSTEM CRT_SYSTEM_NTSC
>to
>
>#define CRT_SYSTEM CRT_SYSTEM_NES
>And then give the 9-bit NES pixels to the crt_modulate function.

I know, during the implementation phase I tried both modes with both the PAL version and the NTSC version. Now I have integrated the PAL_SYSTEM_PAL and CRT_SYSTEM_NTSC modes but I was thinking of also adding the PAL_SYSTEM_NES and CRT_SYSTEM_NES modes by putting a message warning that it will not be possible to change the color palette.

**Comment by LMP88959** [comment] 2023-10-12 18:26
Oh okay. I will see if I can make it possible to have a custom palette and NES artifacts.

**Comment by punesemu** [comment] 2023-10-12 18:30
That would be great and I'm sure it would also be greatly appreciated by other NES emulator authors who want to integrate your filter.

**Comment by LMP88959** [comment] 2023-10-12 21:17
Good news! I added a system to both NTSC-CRT and PAL-CRT to do it. Please use CRT_SYSTEM_NESRGB and PAL_SYSTEM_NESRGB, respectively. The source files are crt_nesrgb.h/.c and pal_nesrgb.h/.c

**Comment by punesemu** [comment] 2023-10-12 21:24
Really?? WOOW! I'm going to integrate it immediately!!

**Comment by LMP88959** [comment] 2023-10-12 21:25
:) Let me know how it goes!

**Comment by punesemu** [comment] 2023-10-12 21:50
Ok I tried both CRT_SYSTEM_NESRGB and PAL_SYSTEM_NESRGB modes and they work great!! Tomorrow morning I will add them but I will also keep the PAL_SYSTEM_PAL and CRT_SYSTEM_NTSC because I like them a lot too. As soon as I complete it I will write to you. Thanks so much for everything!!

**Comment by LMP88959** [comment] 2023-10-12 21:53
No problem! I think you will have a problem with name collisions though because the functions like crt_modulate and all the #defines have the same names so you will need to edit the variable names and function names so they don't collide.

**Comment by punesemu** [comment] 2023-10-13 12:12
Commited https://github.com/punesemu/puNES/commit/6e92dc64079d177dab7e1cb6bfb2ff931e2e130c.

**Comment by LMP88959** [comment] 2023-10-13 15:44
I just tried it out, it looks great!

I noticed something though:
for NES NTSC you need to set the dot_crawl_offset in NTSC_SETTINGS struct automatically every frame (https://github.com/LMP88959/NTSC-CRT/blob/main/crt_nes.h#L136C9-L136C25). It is the same as the burst_phase in blargg's NES filter. It should be either 0, 1, or 2.

Also, if possible, some better default values for brightness, saturation, etc would be nice because when I start it up the image looks very dark.

**Comment by punesemu** [comment] 2023-10-14 07:42
>for NES NTSC you need to set the dot_crawl_offset in NTSC_SETTINGS struct automatically every frame (https://github.com/LMP88959/NTSC-CRT/blob/main/crt_nes.h#L136C9-L136C25). It is the same as the burst_phase in blargg's NES filter. It should be either 0, 1, or 2.

So I have to do something like this every frame:
```C
dot_crawl_offset = (dot_crawl_offset + 1) % 2;
```

>Also, if possible, some better default values for brightness, saturation, etc would be nice because when I start it up the image looks very dark.

I'll check it out when I get home, I'll be out all weekend.
Thanks so much for the support!

**Comment by punesemu** [comment] 2023-10-14 08:26
>for NES NTSC you need to set the dot_crawl_offset in NTSC_SETTINGS struct automatically every frame (https://github.com/LMP88959/NTSC-CRT/blob/main/crt_nes.h#L136C9-L136C25). It is the same as the burst_phase in blargg's NES filter. It should be either 0, 1, or 2.

Okay, I fixed it in a few minutes (https://github.com/punesemu/puNES/commit/46ec6b85026b1ae0466121fee1681308706adee6), the rest will be done on Monday.

**Comment by LMP88959** [comment] 2023-10-14 19:54
> > for NES NTSC you need to set the dot_crawl_offset in NTSC_SETTINGS struct automatically every frame (https://github.com/LMP88959/NTSC-CRT/blob/main/crt_nes.h#L136C9-L136C25). It is the same as the burst_phase in blargg's NES filter. It should be either 0, 1, or 2.
> 
> So I have to do something like this every frame:
> 
> ```c
> dot_crawl_offset = (dot_crawl_offset + 1) % 2;
> ```
> 
> > Also, if possible, some better default values for brightness, saturation, etc would be nice because when I start it up the image looks very dark.
> 
> I'll check it out when I get home, I'll be out all weekend. Thanks so much for the support!

Yes, simliar to that, but with 3 instead of 2:
```c
dot_crawl_offset = (dot_crawl_offset + 1) % 3;
```
Also, I've been playing around with your latest build to try to find good default settings but I am noticing something strange which is that the image has really low contrast. I'm not sure what is causing that because I can't reproduce it on my end using my own code.

These are examples of what it should look like (taken from the BeesNES emulator which implement the filters):
### **NTSC NES**
![NTSCsmb](https://github.com/LMP88959/PAL-CRT/assets/109979235/651bbc93-8eb8-44d4-809e-871fafeead63)

### **PAL NES**
![PALsmb](https://github.com/LMP88959/PAL-CRT/assets/109979235/43928b57-8e14-4b0b-87af-c906295060bb)

The developer of BeesNES uses these settings:
```c
// for NTSC
        m_nnCrtNtsc.hue = 8;
        m_nnCrtNtsc.brightness = 0;
        m_nnCrtNtsc.contrast = 165;
        m_nnCrtNtsc.saturation = 14;
        m_nnCrtNtsc.black_point = 2;
        m_nnCrtNtsc.white_point = 85;
        m_nnCrtNtsc.blend = 1;
```
```c
// for PAL
        m_nnCrtPal.brightness = 0;
        m_nnCrtPal.contrast = 165;
        m_nnCrtPal.saturation = 16;
        m_nnCrtPal.black_point = 2;
        m_nnCrtPal.white_point = 85;
        m_nnCrtPal.blend = 1;

        m_nnCrtPal.chroma_correction = 1;
```

I would appreciate it if you could figure out how to make the default settings produce the above images for NTSC and for PAL respectively.

I hope you enjoy your time away this weekend! Thank you for all the effort you put into your emulator and the integration of my filter!

**Comment by punesemu** [comment] 2023-10-15 20:24
Just out of curiosity, can you try disabling "VBlend" in puNES?

>dot_crawl_offset = (dot_crawl_offset + 1) % 3;

Ops sorry, my haste made me make a mistake.

**Comment by LMP88959** [comment] 2023-10-15 20:31
> Just out of curiosity, can you try disabling "VBlend" in puNES?
> 
> > dot_crawl_offset = (dot_crawl_offset + 1) % 3;
> 
> Ops sorry, my haste made me make a mistake.

VBlend is disabled by default but enabling it just darkens it very slightly, it isnt the cause of the overall dark image.
This is what it looks like for me in puNES.
![screen](https://github.com/LMP88959/PAL-CRT/assets/109979235/c1556aa7-bac7-48a2-a2a9-1585c57407fe)

**Comment by punesemu** [comment] 2023-10-15 20:38
And can you try disabling scanlines too?

**Comment by LMP88959** [comment] 2023-10-15 20:39
> And can you try disabling scanlines too?

Yes this screenshot I posted in my last reply was with scanlines disabled.

**Comment by punesemu** [comment] 2023-10-15 20:41
Ok, thanks so much for the tests, I'm trying to understand what could be the cause of the dark image but so far I haven't succeeded, I'll keep looking.

**Comment by LMP88959** [comment] 2023-10-15 20:41
No problem, I'm not sure if you use Discord but I have a server we can talk in, it might be a bit easier than using github?

**Comment by punesemu** [comment] 2023-10-16 09:08
Here are the results of our investigation https://github.com/punesemu/puNES/commit/f2638cd69c81da9d169ae10b1de9a0f4637faed7

**Comment by LMP88959** [comment] 2023-10-17 02:51
Wow! I just tried it and it looks great!!! Nice job! I will close the issue now.

**Closed as completed by LMP88959** 2023-10-17 02:51 UTC
